-- SPDX-License-Identifier: Apache-2.0
-- Copyright (c) 2026 Leonardo Capossio - bard0 design - <hello@bard0.com>
--
-- AUTO-GENERATED by tools/sync_version.py from the canonical VERSION file
-- at the repo root.  DO NOT EDIT BY HAND -- bump VERSION and re-run
--   python tools/sync_version.py
-- CI runs the same script with --check and fails if this package drifts.

library ieee;
use ieee.std_logic_1164.all;

package fcapz_pkg is
    constant FCAPZ_VERSION_MAJOR : std_logic_vector(7 downto 0) := x"00";
    constant FCAPZ_VERSION_MINOR : std_logic_vector(7 downto 0) := x"04";
    constant FCAPZ_VERSION_PATCH : std_logic_vector(7 downto 0) := x"00";

    constant FCAPZ_ELA_CORE_ID : std_logic_vector(15 downto 0) := x"4C41"; -- "LA" - Logic Analyzer
    constant FCAPZ_EIO_CORE_ID : std_logic_vector(15 downto 0) := x"494F"; -- "IO" - Embedded I/O
    constant FCAPZ_EJTAGAXI_CORE_ID : std_logic_vector(15 downto 0) := x"4A58"; -- "JX" - EJTAG-AXI bridge
    constant FCAPZ_EJTAGUART_CORE_ID : std_logic_vector(15 downto 0) := x"4A55"; -- "JU" - EJTAG-UART bridge

    constant FCAPZ_ELA_VERSION_REG : std_logic_vector(31 downto 0) := FCAPZ_VERSION_MAJOR & FCAPZ_VERSION_MINOR & FCAPZ_ELA_CORE_ID;
    constant FCAPZ_EIO_VERSION_REG : std_logic_vector(31 downto 0) := FCAPZ_VERSION_MAJOR & FCAPZ_VERSION_MINOR & FCAPZ_EIO_CORE_ID;
    constant FCAPZ_EJTAGAXI_VERSION_REG : std_logic_vector(31 downto 0) := FCAPZ_VERSION_MAJOR & FCAPZ_VERSION_MINOR & FCAPZ_EJTAGAXI_CORE_ID;
    constant FCAPZ_EJTAGUART_VERSION_REG : std_logic_vector(31 downto 0) := FCAPZ_VERSION_MAJOR & FCAPZ_VERSION_MINOR & FCAPZ_EJTAGUART_CORE_ID;
end package fcapz_pkg;
