#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Leonardo Capossio - bard0 design - <hello@bard0.com>

"""Compile and run RTL simulations with iverilog + vvp.

Usage:
    python sim/run_sim.py            # run RTL lint + all testbenches
    python sim/run_sim.py --lint-only
    python sim/run_sim.py fcapz_ela   # run specific testbench
    python sim/run_sim.py fcapz_eio
"""

import argparse
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RTL  = ROOT / "rtl"
TB   = ROOT / "tb"
SIM  = ROOT / "sim"

# Each entry: (tb_file, [rtl_sources])
TESTBENCHES = {
    "fcapz_ela": (
        TB / "fcapz_ela_tb.sv",
        [
            RTL / "reset_sync.v",
            RTL / "fcapz_ela.v",
            RTL / "dpram.v",
            RTL / "trig_compare.v",
        ],
    ),
    "fcapz_ela_bug_probe": (
        TB / "fcapz_ela_bug_probe_tb.sv",
        [
            RTL / "reset_sync.v",
            RTL / "fcapz_ela.v",
            RTL / "dpram.v",
            RTL / "trig_compare.v",
        ],
    ),
    "fcapz_eio": (
        TB / "fcapz_eio_tb.sv",
        [
            RTL / "fcapz_eio.v",
        ],
    ),
    "chan_mux": (
        TB / "chan_mux_tb.sv",
        [
            RTL / "reset_sync.v",
            RTL / "fcapz_ela.v",
            RTL / "dpram.v",
            RTL / "trig_compare.v",
        ],
    ),
}

DEFAULT_TESTBENCHES = [
    "fcapz_ela",
    "fcapz_ela_bug_probe",
    "fcapz_eio",
    "chan_mux",
]

LINT_TARGETS = [
    RTL / "dpram.v",
    RTL / "reset_sync.v",
    RTL / "trig_compare.v",
    RTL / "jtag_reg_iface.v",
    RTL / "jtag_burst_read.v",
    RTL / "fcapz_async_fifo.v",
    RTL / "fcapz_ela.v",
    RTL / "fcapz_ela_xilinx7.v",
    RTL / "fcapz_eio.v",
    RTL / "fcapz_eio_xilinx7.v",
    RTL / "fcapz_ejtagaxi.v",
    RTL / "fcapz_ejtagaxi_xilinx7.v",
    RTL / "fcapz_ejtaguart.v",
    RTL / "fcapz_ejtaguart_xilinx7.v",
    RTL / "jtag_tap" / "jtag_tap_xilinxus.v",
    RTL / "fcapz_ela_xilinxus.v",
    RTL / "fcapz_eio_xilinxus.v",
    RTL / "fcapz_ejtagaxi_xilinxus.v",
    RTL / "fcapz_ejtaguart_xilinxus.v",
    # Microchip PolarFire (UJTAG) — requires ujtag_stub.
    RTL / "jtag_tap" / "jtag_tap_polarfire.v",
    RTL / "fcapz_ela_polarfire.v",
    RTL / "fcapz_eio_polarfire.v",
    # Harness that instantiates fcapz_ela_xilinx7 with EIO_EN=1 so the
    # g_shared generate branch is elaborated (default EIO_EN=0 lint
    # would dead-code-eliminate it).
    SIM / "lint_eio_en_xilinx7.v",
]

LINT_STUBS = [
    SIM / "bscane2_stub.v",
    SIM / "xpm_fifo_async_stub.v",
    SIM / "ujtag_stub.v",
]


def run_cmd(cmd: list[str], label: str) -> bool:
    """Run a command, return True on success."""
    print(f"[sim] {label}: {' '.join(str(c) for c in cmd)}", flush=True)
    result = subprocess.run(cmd, text=True)
    if result.returncode != 0:
        print(f"[sim] FAILED: {label}")
        return False
    return True


def run_tb(name: str) -> bool:
    tb_file, rtl_sources = TESTBENCHES[name]
    out_vvp = SIM / f"{name}_tb.vvp"

    # -I rtl makes `include "fcapz_version.vh"` resolvable in any RTL or
    # testbench source.  The header is auto-generated by
    # tools/sync_version.py from the canonical VERSION file at the repo
    # root, so simulation, RTL elaboration, and the Python package
    # version all share the same number.
    ok = run_cmd(
        ["iverilog", "-g2012", "-Wall",
         "-I", str(RTL),
         "-o", str(out_vvp),
         str(tb_file), *[str(s) for s in rtl_sources]],
        f"compile {name}",
    )
    if not ok:
        return False

    return run_cmd(["vvp", str(out_vvp)], f"simulate {name}")


def run_rtl_lint() -> bool:
    out_vvp = SIM / "_lint.vvp"
    common = [
        "iverilog",
        "-Wall",
        "-g2012",
        "-I",
        str(RTL),
        "-y",
        str(RTL),
        "-y",
        str(RTL / "jtag_tap"),
        "-y",
        str(SIM),
        "-o",
        str(out_vvp),
    ]

    ok = True
    for src in LINT_TARGETS:
        cmd = [*common, *[str(s) for s in LINT_STUBS], str(src)]
        if not run_cmd(cmd, f"lint {src.relative_to(ROOT)}"):
            ok = False
    return ok


def main() -> None:
    SIM.mkdir(parents=True, exist_ok=True)

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("testbench", nargs="*", help="testbench name(s) to run")
    parser.add_argument(
        "--lint-only",
        action="store_true",
        help="run iverilog -Wall RTL elaboration lint and skip simulations",
    )
    args = parser.parse_args()

    if not run_rtl_lint():
        sys.exit(1)
    if args.lint_only:
        print(f"\n{'='*60}")
        print(f"RTL lint passed for {len(LINT_TARGETS)} target(s).")
        return

    requested = args.testbench
    if requested:
        unknown = [n for n in requested if n not in TESTBENCHES]
        if unknown:
            print(f"Unknown testbench(es): {unknown}")
            print(f"Available: {list(TESTBENCHES)}")
            sys.exit(1)
        targets = requested
    else:
        targets = DEFAULT_TESTBENCHES

    failures = []
    for name in targets:
        print(f"\n{'='*60}")
        print(f" Running: {name}_tb")
        print(f"{'='*60}")
        if not run_tb(name):
            failures.append(name)

    print(f"\n{'='*60}")
    if failures:
        print(f"FAILED: {failures}")
        sys.exit(1)
    else:
        print(f"All {len(targets)} testbench(es) passed.")


if __name__ == "__main__":
    main()
