# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Leonardo Capossio - bard0 design - <hello@bard0.com>

"""Generate GTKWave ``.gtkw`` sidecars for VCDs from :class:`fcapz.analyzer.Analyzer`."""

from __future__ import annotations

from pathlib import Path

from ..analyzer import CaptureResult

# Must match ``$scope module`` in ``Analyzer.export_vcd_text``.
_VCD_SCOPE = "logic"


def _hier_trace(name: str, width: int, lsb: int) -> str:
    """GTKWave 3.3 expects bit indices on multi-bit vars."""
    if width <= 1:
        return f"{_VCD_SCOPE}.{name}"
    msb = lsb + width - 1
    return f"{_VCD_SCOPE}.{name}[{msb}:{lsb}]"


def _infer_timestamp_width(result: CaptureResult) -> int:
    if not result.timestamps:
        return 32
    m = max(result.timestamps)
    return max(m.bit_length(), 1)


def write_gtkw_for_capture(
    result: CaptureResult,
    vcd_path: Path,
    gtkw_path: Path,
    *,
    timestamp_width: int | None = None,
) -> None:
    """
    Write a minimal save file so GTKWave opens the dump with traces pre-added.

    Paths are written with POSIX slashes inside quotes (GTKWave accepts this on
    Windows too).
    """
    cfg = result.config
    vcd_abs = vcd_path.resolve().as_posix()
    gtkw_abs = gtkw_path.resolve().as_posix()

    traces: list[str] = []
    if cfg.probes:
        for p in cfg.probes:
            traces.append(_hier_trace(p.name, p.width, p.lsb))
    else:
        traces.append(_hier_trace("sample", cfg.sample_width, 0))
    if result.timestamps:
        tw = timestamp_width if timestamp_width is not None else _infer_timestamp_width(
            result,
        )
        traces.append(_hier_trace("timestamp", tw, 0))

    # @22: hex data format for following signals (GTKWave 3.3 analyzer flags).
    lines = [
        "[*]",
        f'[dumpfile] "{vcd_abs}"',
        f'[savefile] "{gtkw_abs}"',
        "[timestart] 0",
        f"[treeopen] {_VCD_SCOPE}.",
        "",
        "[*] Generated by fpgacapzero — add/remove traces in GTKWave as needed.",
        "",
        "@22",
        *traces,
        "",
    ]
    gtkw_path.parent.mkdir(parents=True, exist_ok=True)
    gtkw_path.write_text("\n".join(lines), encoding="utf-8")
