# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Leonardo Capossio - bard0 design - <hello@bard0.com>

"""Merged waveform export for comparing captures from multiple ELA cores."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from ..analyzer import CaptureResult, vcd_simulation_times


@dataclass(frozen=True)
class WaveCapture:
    label: str
    result: CaptureResult


def _vcd_id(n: int) -> str:
    """Return a compact printable VCD identifier."""
    chars = [chr(i) for i in range(33, 127)]
    base = len(chars)
    out = ""
    while True:
        out = chars[n % base] + out
        n = n // base - 1
        if n < 0:
            return out


def _scope_name(label: str, fallback: str) -> str:
    clean = "".join(ch if ch.isalnum() or ch == "_" else "_" for ch in label.strip())
    if not clean:
        clean = fallback
    if clean[0].isdigit():
        clean = f"cap_{clean}"
    return clean


def _signal_defs(result: CaptureResult) -> list[tuple[str, int, int]]:
    cfg = result.config
    if cfg.probes:
        return [(p.name, p.width, p.lsb) for p in cfg.probes]
    return [("sample", cfg.sample_width, 0)]


def _period_ns(result: CaptureResult) -> int:
    return max(1, int(round(1_000_000_000 / result.config.sample_clock_hz)))


def _global_times(result: CaptureResult, trigger_origin_ns: int) -> list[int]:
    local_ticks = vcd_simulation_times(result)
    if not local_ticks:
        return []
    period = _period_ns(result)
    local_ns = [int(t) * period for t in local_ticks]
    pre = int(result.config.pretrigger)
    if 0 <= pre < len(local_ns):
        trigger_ns = local_ns[pre]
    else:
        trigger_ns = local_ns[0]
    offset = max(0, trigger_origin_ns - trigger_ns)
    return [offset + t for t in local_ns]


def merged_trigger_time_ns(captures: list[WaveCapture]) -> int:
    trigger_origin_ns = 0
    for cap in captures:
        if not cap.result.samples:
            continue
        local_ticks = vcd_simulation_times(cap.result)
        pre = int(cap.result.config.pretrigger)
        if 0 <= pre < len(local_ticks):
            trigger_origin_ns = max(
                trigger_origin_ns,
                int(local_ticks[pre]) * _period_ns(cap.result),
            )
    return trigger_origin_ns


def export_merged_vcd_text(captures: list[WaveCapture]) -> str:
    """Export captures as one VCD with scopes aligned at trigger index."""
    captures = [c for c in captures if c.result.samples]
    if not captures:
        raise ValueError("no non-empty captures to export")

    trigger_origin_ns = merged_trigger_time_ns(captures)

    var_counter = 0
    scopes: list[tuple[str, WaveCapture, list[tuple[str, str, int, int]], str]] = []
    for idx, cap in enumerate(captures):
        scope = _scope_name(cap.label, f"capture_{idx}")
        signals = []
        for name, width, lsb in _signal_defs(cap.result):
            signals.append((_vcd_id(var_counter), _scope_name(name, "sample"), width, lsb))
            var_counter += 1
        ts_id = ""
        if cap.result.timestamps:
            ts_id = _vcd_id(var_counter)
            var_counter += 1
        scopes.append((scope, cap, signals, ts_id))

    lines = [
        "$date",
        "  generated by fcapz",
        "$end",
        "$version",
        "  fcapz-multi-capture",
        "$end",
        "$timescale",
        "  1 ns",
        "$end",
        "$scope module fcapz $end",
    ]
    for scope, cap, signals, ts_id in scopes:
        lines.append(f"$scope module {scope} $end")
        for var_id, name, width, _ in signals:
            lines.append(f"$var wire {width} {var_id} {name} $end")
        if ts_id:
            tw = max(1, max(int(t).bit_length() for t in cap.result.timestamps))
            lines.append(f"$var wire {tw} {ts_id} timestamp $end")
        lines.append("$upscope $end")
    lines.extend(["$upscope $end", "$enddefinitions $end", "$dumpvars"])
    for _, cap, signals, ts_id in scopes:
        for var_id, _, width, _ in signals:
            lines.append(f"b{'0' * width} {var_id}")
        if ts_id:
            tw = max(1, max(int(t).bit_length() for t in cap.result.timestamps))
            lines.append(f"b{'0' * tw} {ts_id}")
    lines.append("$end")

    events: dict[int, list[str]] = {}
    for _, cap, signals, ts_id in scopes:
        times = _global_times(cap.result, trigger_origin_ns)
        for i, sample in enumerate(cap.result.samples):
            changes = events.setdefault(times[i], [])
            for var_id, _, width, lsb in signals:
                val = (int(sample) >> lsb) & ((1 << width) - 1)
                changes.append(f"b{val:0{width}b} {var_id}")
            if ts_id and i < len(cap.result.timestamps):
                tw = max(1, max(int(t).bit_length() for t in cap.result.timestamps))
                changes.append(f"b{int(cap.result.timestamps[i]):0{tw}b} {ts_id}")

    for t in sorted(events):
        lines.append(f"#{t}")
        lines.extend(events[t])
    return "\n".join(lines) + "\n"


def write_merged_vcd(captures: list[WaveCapture], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(export_merged_vcd_text(captures), encoding="ascii")


def merged_signal_paths(captures: list[WaveCapture]) -> list[str]:
    paths: list[str] = []
    for idx, cap in enumerate(captures):
        scope = _scope_name(cap.label, f"capture_{idx}")
        for name, _, _ in _signal_defs(cap.result):
            paths.append(f"fcapz.{scope}.{_scope_name(name, 'sample')}")
        if cap.result.timestamps:
            paths.append(f"fcapz.{scope}.timestamp")
    return paths


def _merged_gtkw_traces(captures: list[WaveCapture]) -> list[str]:
    traces: list[str] = []
    for idx, cap in enumerate(captures):
        scope = _scope_name(cap.label, f"capture_{idx}")
        for name, width, lsb in _signal_defs(cap.result):
            clean = _scope_name(name, "sample")
            if width <= 1:
                traces.append(f"fcapz.{scope}.{clean}")
            else:
                traces.append(f"fcapz.{scope}.{clean}[{lsb + width - 1}:{lsb}]")
        if cap.result.timestamps:
            tw = max(1, max(int(t).bit_length() for t in cap.result.timestamps))
            traces.append(f"fcapz.{scope}.timestamp[{tw - 1}:0]")
    return traces


def write_merged_surfer_command_file(captures: list[WaveCapture], path: Path) -> None:
    paths = merged_signal_paths(captures)
    trigger_time = merged_trigger_time_ns(captures)
    lines = [
        "# Generated by fpgacapzero - safe to edit or delete.",
        "module_add fcapz",
        "add_variables " + " ".join(paths),
        f"cursor_set {trigger_time}",
        "marker_set fcapz_trigger",
        "item_set_color blue",
        "goto_marker fcapz_trigger",
        "",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def write_merged_gtkw(captures: list[WaveCapture], vcd_path: Path, gtkw_path: Path) -> None:
    traces = _merged_gtkw_traces(captures)
    lines = [
        "[*]",
        f'[dumpfile] "{vcd_path.resolve().as_posix()}"',
        f'[savefile] "{gtkw_path.resolve().as_posix()}"',
        "[timestart] 0",
        "[treeopen] fcapz.",
        "",
        "[*] Generated by fcapz - add/remove traces in GTKWave as needed.",
        "",
        "@22",
        *traces,
        "",
    ]
    gtkw_path.parent.mkdir(parents=True, exist_ok=True)
    gtkw_path.write_text("\n".join(lines), encoding="utf-8")
