# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Leonardo Capossio - bard0 design - <hello@bard0.com>

"""
Generate a Surfer ``--command-file`` for pre-loading traces after opening a VCD.

Surfer runs these as in-app CLI commands once the waveform is loaded. Syntax is
documented in upstream ``surfer --help`` (lines or ``;``, ``#`` comments).
"""

from __future__ import annotations

from pathlib import Path

from ..analyzer import CaptureResult

# Must match ``$scope module`` in ``Analyzer.export_vcd_text``.
_VCD_SCOPE = "logic"


def _signal_paths(result: CaptureResult) -> list[str]:
    cfg = result.config
    paths: list[str] = []
    if cfg.probes:
        for p in cfg.probes:
            paths.append(f"{_VCD_SCOPE}.{p.name}")
    else:
        paths.append(f"{_VCD_SCOPE}.sample")
    if result.timestamps:
        paths.append(f"{_VCD_SCOPE}.timestamp")
    return paths


def write_surfer_command_file_for_capture(
    result: CaptureResult,
    command_path: Path,
) -> None:
    """
    Write commands so Surfer adds the same signals as our GTKWave sidecar.

    Typical launch::

        surfer dump.vcd --command-file dump.surfer.txt
    """
    paths = _signal_paths(result)
    lines = [
        "# Generated by fpgacapzero — safe to edit or delete.",
        f"module_add {_VCD_SCOPE}",
        "add_variables " + " ".join(paths),
        "",
    ]
    command_path.parent.mkdir(parents=True, exist_ok=True)
    command_path.write_text("\n".join(lines), encoding="utf-8")
