# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Leonardo Capossio - bard0 design - <hello@bard0.com>

"""
Generate a Surfer ``--command-file`` for pre-loading traces after opening a VCD.

Surfer runs these as in-app CLI commands once the waveform is loaded. Syntax is
documented in upstream ``surfer --help`` (lines or ``;``, ``#`` comments).

After variables are added, we move the cursor to the ELA trigger sample time
(same integer units as VCD ``#`` times from :func:`~fcapz.analyzer.vcd_simulation_times`),
place a named marker there, tint it with Surfer's ``item_set_color`` (theme color
name), then scroll via ``goto_marker``.
"""

from __future__ import annotations

from pathlib import Path

from ..analyzer import CaptureResult, vcd_simulation_times

# Must match ``$scope module`` in ``Analyzer.export_vcd_text``.
_VCD_SCOPE = "logic"

# Surfer batch commands: ``cursor_set <time>``, ``marker_set <name>``,
# ``item_set_color``, ``goto_marker``.
_TRIGGER_MARKER_NAME = "fcapz_trigger"
# Theme color key (case-insensitive in Surfer); change in the command file if your theme differs.
_TRIGGER_MARKER_COLOR = "blue"


def _surfer_trigger_time_str(result: CaptureResult) -> str | None:
    """VCD ``#`` time at the committed trigger sample index (``pretrigger``)."""
    n = len(result.samples)
    if n == 0:
        return None
    idx = int(result.config.pretrigger)
    if idx < 0 or idx >= n:
        return None
    times = vcd_simulation_times(result)
    return str(times[idx])


def surfer_signal_paths(result: CaptureResult) -> list[str]:
    cfg = result.config
    paths: list[str] = []
    if cfg.probes:
        for p in cfg.probes:
            paths.append(f"{_VCD_SCOPE}.{p.name}")
    else:
        paths.append(f"{_VCD_SCOPE}.sample")
    if result.timestamps:
        paths.append(f"{_VCD_SCOPE}.timestamp")
    return paths


def write_surfer_command_file_for_capture(
    result: CaptureResult,
    command_path: Path,
) -> None:
    """
    Write commands so Surfer adds the same signals as our GTKWave sidecar.

    Typical launch::

        surfer dump.vcd --command-file dump.surfer.txt
    """
    paths = surfer_signal_paths(result)
    lines = [
        "# Generated by fpgacapzero — safe to edit or delete.",
        f"module_add {_VCD_SCOPE}",
        "add_variables " + " ".join(paths),
    ]
    t = _surfer_trigger_time_str(result)
    if t is not None:
        lines.extend(
            [
                f"# ELA trigger sample (pretrigger={int(result.config.pretrigger)})",
                f"cursor_set {t}",
                f"marker_set {_TRIGGER_MARKER_NAME}",
                f"item_set_color {_TRIGGER_MARKER_COLOR}",
                f"goto_marker {_TRIGGER_MARKER_NAME}",
            ],
        )
    lines.append("")
    command_path.parent.mkdir(parents=True, exist_ok=True)
    command_path.write_text("\n".join(lines), encoding="utf-8")
