#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Leonardo Capossio - bard0 design - <hello@bard0.com>
"""Generate the parts of the user manual that come from the code.

* docs/10_cli_reference.md: every block between
  ``<!-- BEGIN GENERATED cli:KEY ... -->`` and ``<!-- END GENERATED cli:KEY -->``
  is rebuilt from ``fcapz.cli.build_parser()``:

  - ``cli:global``     the options that come before the subcommand
  - ``cli:subcommands`` the one-line summary of every subcommand
  - ``cli:NAME``        usage and options of subcommand NAME
  - ``cli:NAME/BASE``   the options NAME has and BASE does not

  Every subcommand must appear in some block, so a new one cannot go
  undocumented.  The prose around the blocks stays hand-written.

* docs/specs/python_api.md is written in full from the docstrings and
  signatures of the public ``fcapz`` API.

Usage::

    python tools/gen_docs.py           # rewrite the generated parts
    python tools/gen_docs.py --check   # exit 1 if they are out of date (CI)
"""

from __future__ import annotations

import argparse
import dataclasses
import enum
import inspect
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CLI_DOC = ROOT / "docs" / "10_cli_reference.md"
API_DOC = ROOT / "docs" / "specs" / "python_api.md"

# Must match GENERATED_PAGE_MARK in tools/mkdocs_hooks.py.
GENERATED_PAGE_MARK = "<!-- Generated by tools/gen_docs.py"

_BLOCK = re.compile(
    r"(<!-- BEGIN GENERATED (?P<key>\S+)[^\n]*-->\n)(?P<body>.*?)(<!-- END GENERATED (?P=key) -->)",
    re.S,
)


def _import_fcapz():
    host = str(ROOT / "host")
    if host not in sys.path:
        sys.path.insert(0, host)
    import fcapz
    import fcapz.cli
    import fcapz.transport

    return fcapz


# -- CLI ---------------------------------------------------------------------


def _cell(text: str) -> str:
    return " ".join(text.split()).replace("|", "\\|")


def _code_cell(text: str) -> str:
    """Inline code for a table cell.  GitHub and Python-Markdown disagree on
    an escaped pipe inside backticks, so such cells use <code> instead."""
    text = " ".join(text.split())
    if "|" not in text:
        return f"`{text}`"
    escaped = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    return "<code>" + escaped.replace("|", "&#124;") + "</code>"


def _help(action: argparse.Action) -> str:
    text = action.help or ""
    if "%" in text:
        text = text % {**vars(action), "prog": "fcapz"}
    return _cell(text)


def _flag(action: argparse.Action) -> str:
    if not action.option_strings:
        return action.metavar or action.dest.upper()
    name = max(action.option_strings, key=len)
    if action.nargs == 0:
        return name
    if action.metavar:
        return f"{name} {action.metavar}"
    if action.choices:
        return f"{name} {{{','.join(action.choices)}}}"
    return f"{name} {action.dest.upper()}"


def _default(action: argparse.Action) -> str:
    if action.required:
        return "required"
    if action.nargs == 0:
        return "off"
    if action.default is None:
        return "—"
    value = action.default
    if isinstance(value, int) and value > 9 and "hex" in (action.help or "").lower():
        return f"`{value:#x}`"
    return _code_cell(str(value))


def _options(parser: argparse.ArgumentParser) -> list[argparse.Action]:
    return [
        a
        for a in parser._actions
        if not isinstance(a, (argparse._HelpAction, argparse._SubParsersAction))
    ]


def _subparsers(parser: argparse.ArgumentParser):
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            return action
    raise RuntimeError("fcapz parser has no subcommands")


def _groups(parser: argparse.ArgumentParser):
    return [g for g in parser._mutually_exclusive_groups if g._group_actions]


def _usage(name: str, parser: argparse.ArgumentParser) -> str:
    grouped = {a for g in _groups(parser) for a in g._group_actions}
    flags = [a for a in _options(parser) if a.option_strings and a not in grouped]
    parts = [_flag(a) for a in flags if a.required]
    optional = [_flag(a) for a in flags if not a.required]
    # A long list of optional flags is what the table below is for.
    parts += ["[options]"] if len(optional) > 4 else [f"[{f}]" for f in optional]
    for group in _groups(parser):
        alts = " | ".join(_flag(a) for a in group._group_actions)
        parts.append(f"({alts})" if group.required else f"[{alts}]")
    parts += [_flag(a) for a in _options(parser) if not a.option_strings]
    return " ".join(["fcapz [global options]", name, *parts])


def _option_table(actions: list[argparse.Action]) -> list[str]:
    lines = ["| Option | Default | Description |", "|---|---|---|"]
    for action in actions:
        lines.append(f"| `{_flag(action)}` | {_default(action)} | {_help(action)} |")
    return lines


def _cli_block(key: str, parser: argparse.ArgumentParser) -> str:
    subs = _subparsers(parser)
    if key == "global":
        lines = _option_table(_options(parser))
    elif key == "subcommands":
        lines = ["| Subcommand | What it does |", "|---|---|"]
        lines += [f"| `{c.dest}` | {_cell(c.help or '')} |" for c in subs._choices_actions]
    else:
        name, _, base = key.partition("/")
        if name not in subs.choices or (base and base not in subs.choices):
            raise SystemExit(f"{CLI_DOC.name}: unknown subcommand in block cli:{key}")
        sub = subs.choices[name]
        actions = _options(sub)
        lines = [f"Usage: `{_usage(name, sub)}`", ""]
        if base:
            have = {a.dest for a in _options(subs.choices[base])}
            actions = [a for a in actions if a.dest not in have]
            lines = [f"Options `{name}` has in addition to those of `{base}`:", ""]
        if actions:
            lines += _option_table(actions)
        else:
            lines.append("No options of its own; the [global options](#global-options) apply.")
        for group in _groups(sub):
            if group.required and not base:
                names = [max(a.option_strings, key=len) for a in group._group_actions]
                flags = ", ".join(f"`{n}`" for n in names)
                lines += ["", f"Exactly one of {flags} is required."]
    return "\n".join(["", *lines, ""]) + "\n"


def render_cli_doc(text: str, parser: argparse.ArgumentParser) -> str:
    """Return ``text`` with every generated CLI block rebuilt from ``parser``."""
    covered = set()

    def fill(match: re.Match) -> str:
        key = match.group("key")
        if not key.startswith("cli:"):
            raise SystemExit(f"{CLI_DOC.name}: unknown generated block {key}")
        covered.add(key[4:].partition("/")[0])
        body = _cli_block(key[4:], parser)
        return f"{match.group(1)}{body}{match.group(4)}"

    out = _BLOCK.sub(fill, text)
    missing = [n for n in _subparsers(parser).choices if n not in covered]
    for key in ("global", "subcommands"):
        if key not in covered:
            missing.append(key)
    if missing:
        raise SystemExit(f"{CLI_DOC.name}: no generated block for {', '.join(missing)}")
    return out


# -- Python API ----------------------------------------------------------------

_ROLE = re.compile(r":(?:py:)?(?:meth|class|func|attr|exc|data|mod|obj):`~?([^`]+)`")


def _stable_repr(value) -> str:
    """repr() that does not depend on hash seeds or object addresses."""
    if isinstance(value, enum.Enum):
        return f"{type(value).__name__}.{value.name}"
    if isinstance(value, dict):
        items = ", ".join(f"{_stable_repr(k)}: {_stable_repr(v)}" for k, v in value.items())
        return "{" + items + "}"
    if isinstance(value, (set, frozenset)):
        items = ", ".join(sorted(_stable_repr(v) for v in value))
        return f"{type(value).__name__}({{{items}}})" if value else f"{type(value).__name__}()"
    if isinstance(value, (list, tuple)):
        items = ", ".join(_stable_repr(v) for v in value)
        if isinstance(value, tuple):
            return f"({items},)" if len(value) == 1 else f"({items})"
        return f"[{items}]"
    if callable(value) and hasattr(value, "__qualname__"):
        return value.__qualname__
    text = repr(value)
    if " at 0x" in text:
        return f"<{type(value).__name__}>"
    return text


def _annotation(annotation) -> str:
    if annotation is inspect.Parameter.empty:
        return ""
    if isinstance(annotation, str):
        return annotation
    return inspect.formatannotation(annotation)


def _signature(name: str, obj, drop_first: bool = False) -> str:
    try:
        sig = inspect.signature(obj)
    except (TypeError, ValueError):
        return f"{name}(...)"
    params = list(sig.parameters.values())
    if drop_first and params and params[0].name in ("self", "cls"):
        params = params[1:]
    parts = []
    seen_kw_only = False
    for i, param in enumerate(params):
        kind = param.kind
        if kind is param.KEYWORD_ONLY and not seen_kw_only:
            parts.append("*")
        if kind in (param.KEYWORD_ONLY, param.VAR_POSITIONAL):
            seen_kw_only = True
        text = param.name
        if kind is param.VAR_POSITIONAL:
            text = "*" + text
        elif kind is param.VAR_KEYWORD:
            text = "**" + text
        ann = _annotation(param.annotation)
        if ann:
            text += f": {ann}"
        if param.default is not param.empty:
            default = _stable_repr(param.default)
            text += f" = {default}" if ann else f"={default}"
        parts.append(text)
        if kind is param.POSITIONAL_ONLY and (
            i + 1 == len(params) or params[i + 1].kind is not param.POSITIONAL_ONLY
        ):
            parts.append("/")
    ret = _annotation(sig.return_annotation)
    tail = f" -> {ret}" if ret else ""
    one_line = f"{name}({', '.join(parts)}){tail}"
    if len(one_line) <= 88:
        return one_line
    inner = "".join(f"    {p},\n" for p in parts)
    return f"{name}(\n{inner}){tail}"


# Google-style docstring sections.
_LIST_SECTIONS = {"Args", "Arguments", "Parameters", "Raises", "Attributes"}
_TEXT_SECTIONS = {"Returns", "Return", "Yields", "Note", "Notes"}
_CODE_SECTIONS = {"Example", "Examples"}
_ITEM_NAME = re.compile(r"^([\w.*]+)(\s*\([^)]*\))?:\s")


def _escape(line: str) -> str:
    """Markdown-escape a docstring text line (code spans are left alone)."""
    if line.lstrip().startswith("#"):
        line = line.replace("#", "\\#", 1)
    # Keep <...> literal outside code spans (GitHub would drop it as HTML).
    pieces = line.split("`")
    for k in range(0, len(pieces), 2):
        pieces[k] = pieces[k].replace("<", "&lt;").replace(">", "&gt;")
    return "`".join(pieces)


def _indent(line: str) -> int:
    return len(line) - len(line.lstrip())


def _section(title: str, header: str, block: list[str]) -> list[str]:
    base = min(_indent(b) for b in block if b.strip())
    if title in _LIST_SECTIONS:
        items: list[str] = []
        for b in block:
            if not b.strip():
                continue
            if _indent(b) == base or not items:
                text = b.strip()
                name = _ITEM_NAME.match(text)
                if name:
                    text = f"`{name.group(1)}`{name.group(2) or ''}:{text[name.end() - 1 :]}"
                items.append(text)
            else:
                items[-1] += " " + b.strip()
        return [f"**{title}:**", "", *(f"- {_escape(t)}" for t in items)]
    dedented = [b[base:] if b.strip() else "" for b in block]
    if title in _TEXT_SECTIONS:
        return [f"**{title}:**", "", *(_escape(b.strip()) for b in block)]
    lang = "python" if title in _CODE_SECTIONS else "text"
    head = f"**{title}:**" if title in _CODE_SECTIONS else _escape(header.rstrip(":") + ":")
    return [head, "", f"```{lang}", *dedented, "```"]


def _docstring(obj) -> str:
    doc = inspect.getdoc(obj) or ""
    doc = _ROLE.sub(r"`\1`", doc).replace("``", "`")
    lines = doc.split("\n")
    out: list[str] = []
    i = 0
    while i < len(lines):
        line = lines[i]
        j = i + 1
        while j < len(lines) and not lines[j].strip():
            j += 1
        starts_block = j < len(lines) and _indent(lines[j]) > 0
        if line.rstrip().endswith(":") and _indent(line) == 0 and starts_block:
            # A header followed by an indented block: a section or a literal.
            end = j
            while end < len(lines) and (not lines[end].strip() or _indent(lines[end]) > 0):
                end += 1
            block = lines[j:end]
            while block and not block[-1].strip():
                block.pop()
            out += _section(line.rstrip().rstrip(":"), line.rstrip(), block)
            out.append("")
            i = end
            continue
        out.append(_escape(line))
        i += 1
    return "\n".join(out).strip()


def _field_comments(cls) -> dict[str, str]:
    """The ``# comment`` after each dataclass field, with comment-only
    continuation lines, as the field's description."""
    comments: dict[str, list[str]] = {}
    current = None
    for line in inspect.getsource(cls).split("\n")[1:]:
        field_line = re.match(r"\s+(\w+)\s*:[^#]*(?:#\s?(.*))?$", line)
        continued = re.match(r"\s+#\s?(.*)$", line)
        if field_line and not line.strip().startswith(("def ", "@", '"')):
            current = field_line.group(1)
            comments[current] = [field_line.group(2)] if field_line.group(2) else []
        elif continued and current and comments[current]:
            comments[current].append(continued.group(1))
        else:
            current = None
    return {k: _cell(" ".join(v)) for k, v in comments.items() if v}


def _is_auto_dataclass_doc(cls) -> bool:
    return dataclasses.is_dataclass(cls) and (cls.__doc__ or "").startswith(f"{cls.__name__}(")


def _code(text: str) -> list[str]:
    return ["```python", text, "```"]


def _class_section(qualname: str, cls) -> list[str]:
    lines = [f"### `{qualname}`", ""]
    bases = [b.__name__ for b in cls.__bases__ if b is not object]
    if dataclasses.is_dataclass(cls):
        lines += _code(f"@dataclass\nclass {cls.__name__}")
    else:
        init = cls.__dict__.get("__init__")
        lines += _code(_signature(cls.__name__, init, drop_first=True) if init else cls.__name__)
    if bases:
        lines += ["", "Subclass of " + ", ".join(f"`{b}`" for b in bases) + "."]
    if not _is_auto_dataclass_doc(cls) and _docstring(cls):
        lines += ["", _docstring(cls)]
    if dataclasses.is_dataclass(cls):
        comments = _field_comments(cls)
        lines += ["", "| Field | Type | Default | Description |", "|---|---|---|---|"]
        for f in dataclasses.fields(cls):
            if f.default is not dataclasses.MISSING:
                default = _code_cell(_stable_repr(f.default))
            elif f.default_factory is not dataclasses.MISSING:
                default = _code_cell(_stable_repr(f.default_factory) + "()")
            else:
                default = "required"
            ftype = _code_cell(_annotation(f.type))
            lines.append(f"| `{f.name}` | {ftype} | {default} | {comments.get(f.name, '')} |")
    constants = [
        (n, v)
        for n, v in cls.__dict__.items()
        if n.isupper() and not callable(v) and not isinstance(v, (property, classmethod))
    ]
    if constants:
        lines += ["", "Class constants:", ""]
        lines += _code("\n".join(f"{n} = {_stable_repr(v)}" for n, v in constants))
    for name, member in cls.__dict__.items():
        if name.startswith("_"):
            continue
        if isinstance(member, property):
            ret = _annotation(inspect.signature(member.fget).return_annotation)
            lines += ["", f"#### `{cls.__name__}.{name}`", ""]
            lines += _code(f"@property\n{name}" + (f" -> {ret}" if ret else ""))
        elif isinstance(member, (staticmethod, classmethod)):
            func = member.__func__
            lines += ["", f"#### `{cls.__name__}.{name}`", ""]
            deco = "@staticmethod" if isinstance(member, staticmethod) else "@classmethod"
            drop = isinstance(member, classmethod)
            lines += _code(f"{deco}\n{_signature(name, func, drop_first=drop)}")
            member = func
        elif inspect.isfunction(member):
            lines += ["", f"#### `{cls.__name__}.{name}`", ""]
            lines += _code(_signature(name, member, drop_first=True))
        else:
            continue
        doc = _docstring(member.fget if isinstance(member, property) else member)
        if doc:
            lines += ["", doc]
    return lines


def _api_objects(fcapz):
    names = [n for n in fcapz.__all__ if not n.startswith("_")]
    objects = [(n, getattr(fcapz, n)) for n in names]
    # Documented in chapter 09 although not exported from the package root.
    at = names.index("XilinxHwServerTransport") + 1
    objects.insert(at, ("QuartusStpTransport", fcapz.transport.QuartusStpTransport))
    return objects


def render_api_doc() -> str:
    fcapz = _import_fcapz()
    lines = [
        f"{GENERATED_PAGE_MARK} from the fcapz docstrings; do not edit. -->",
        "",
        "# Python API reference",
        "",
        "Every public name of the `fcapz` package, with its signature and docstring,",
        "generated from the code by `tools/gen_docs.py` (CI fails if this page is",
        "out of date).  For a guided tour with worked examples, read",
        "[chapter 09](../09_python_api.md) first.",
    ]
    module = None
    for name, obj in _api_objects(fcapz):
        if name == "__version__":
            continue
        mod = getattr(obj, "__module__", None) if not isinstance(obj, (str, int)) else None
        mod = mod or "fcapz"
        if mod != module:
            module = mod
            lines += ["", f"## `{module}`"]
        lines.append("")
        if inspect.isclass(obj):
            lines += _class_section(name, obj)
        elif callable(obj):
            lines += [f"### `{name}`", ""]
            lines += _code(_signature(name, obj))
            if _docstring(obj):
                lines += ["", _docstring(obj)]
        else:
            lines += [f"### `{name}`", ""]
            lines += _code(f"{name} = {_stable_repr(obj)}")
    return "\n".join(lines) + "\n"


# -- driver ----------------------------------------------------------------------


def generate() -> dict[Path, str]:
    """Return the up-to-date text of every generated file."""
    fcapz = _import_fcapz()
    cli_text = CLI_DOC.read_text(encoding="utf-8")
    return {
        CLI_DOC: render_cli_doc(cli_text, fcapz.cli.build_parser()),
        API_DOC: render_api_doc(),
    }


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--check", action="store_true", help="fail if a generated part is stale")
    args = ap.parse_args(argv)
    stale = []
    for path, text in generate().items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == text:
            continue
        stale.append(path.relative_to(ROOT).as_posix())
        if not args.check:
            path.write_text(text, encoding="utf-8", newline="\n")
    if args.check and stale:
        print(
            "Generated docs are out of date: " + ", ".join(stale) + "\n"
            "Run: python tools/gen_docs.py",
            file=sys.stderr,
        )
        return 1
    for name in stale:
        print(f"updated {name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
