#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Leonardo Capossio - bard0 design - <hello@bard0.com>

"""Generate HDL version constants from the canonical VERSION file.

Single source of truth: ``VERSION`` at the repo root holds a semver string
(``MAJOR.MINOR.PATCH``).  This script regenerates ``rtl/fcapz_version.vh``
and ``rtl/vhdl/pkg/fcapz_pkg.vhd`` so RTL, simulation testbenches, the Python package version
(``pyproject.toml`` ``dynamic = ["version"]``), and the
``fcapz.__version__`` runtime attribute all share the same number.

Usage
-----
    python tools/sync_version.py            # regenerate HDL version constants
    python tools/sync_version.py --check    # exit non-zero if drift detected
                                            # (used by CI to block merges)

The script never edits ``pyproject.toml`` or any Python file; those read
the VERSION file directly via setuptools' ``dynamic`` mechanism and the
``fcapz.__version__`` reader.  Only HDL constants are generated here.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
VERSION_FILE = ROOT / "VERSION"
HEADER_FILE = ROOT / "rtl" / "fcapz_version.vh"
VHDL_PACKAGE_FILE = ROOT / "rtl" / "vhdl" / "pkg" / "fcapz_pkg.vhd"

# Per-core 16-bit ASCII identifiers packed into the low half of each core's
# VERSION register.  These are constants tied to the core, not the version.
# When new cores are added, append their identifier here so the header
# documents the project-wide ID space in one place.
CORE_IDS: dict[str, tuple[str, str]] = {
    "ELA":  ("LA", "Logic Analyzer"),
    "EIO":  ("IO", "Embedded I/O"),
    "EJTAGAXI":  ("JX", "EJTAG-AXI bridge"),
    "EJTAGUART": ("JU", "EJTAG-UART bridge"),
}


def parse_version(text: str) -> tuple[int, int, int]:
    """Parse a semver string ``MAJOR.MINOR.PATCH`` from the VERSION file.

    Raises ValueError on malformed input or out-of-range numbers (each
    component must fit in 8 bits because the RTL VERSION register
    allocates one byte per component).
    """
    text = text.strip()
    m = re.fullmatch(r"(\d+)\.(\d+)\.(\d+)", text)
    if not m:
        raise ValueError(
            f"VERSION file content {text!r} is not of form MAJOR.MINOR.PATCH"
        )
    major, minor, patch = int(m.group(1)), int(m.group(2)), int(m.group(3))
    for label, value in (("major", major), ("minor", minor), ("patch", patch)):
        if not (0 <= value <= 0xFF):
            raise ValueError(
                f"VERSION {label}={value} does not fit in 8 bits (0..255)"
            )
    return major, minor, patch


def render_header(major: int, minor: int, patch: int, version_str: str) -> str:
    """Build the contents of rtl/fcapz_version.vh from a parsed version."""
    lines: list[str] = [
        "// SPDX-License-Identifier: Apache-2.0",
        "// Copyright (c) 2026 Leonardo Capossio - bard0 design - <hello@bard0.com>",
        "//",
        "// AUTO-GENERATED by tools/sync_version.py from the canonical VERSION file",
        "// at the repo root.  DO NOT EDIT BY HAND -- bump VERSION and re-run",
        "//   python tools/sync_version.py",
        "// CI runs the same script with --check and fails if this header drifts.",
        "",
        "`ifndef FCAPZ_VERSION_VH",
        "`define FCAPZ_VERSION_VH",
        "",
        f"`define FCAPZ_VERSION_MAJOR  8'h{major:02X}",
        f"`define FCAPZ_VERSION_MINOR  8'h{minor:02X}",
        f"`define FCAPZ_VERSION_PATCH  8'h{patch:02X}",
        f'`define FCAPZ_VERSION_STRING "{version_str}"',
        "",
        "// Per-core 16-bit ASCII identifiers, packed into VERSION[15:0] of",
        "// each core's identity register.  Constant per-core; never zero.",
    ]
    for core_name, (ascii_id, description) in CORE_IDS.items():
        if len(ascii_id) != 2:
            raise ValueError(f"core_id {ascii_id!r} for {core_name} must be 2 ASCII chars")
        packed = (ord(ascii_id[0]) << 8) | ord(ascii_id[1])
        lines.append(
            f"`define FCAPZ_{core_name}_CORE_ID 16'h{packed:04X}  "
            f'// "{ascii_id}" - {description}'
        )
    lines += [
        "",
        "// Packed VERSION registers for each core (read at addr 0x0000 of",
        "// the core's register space).  Layout:",
        "//   [31:24] major (8-bit)",
        "//   [23:16] minor (8-bit)",
        "//   [15:0]  core_id (ASCII, constant per-core)",
        "//",
        "// Hosts must verify the low-16 magic before trusting any other",
        "// register on the same chain.",
    ]
    for core_name in CORE_IDS:
        lines.append(
            f"`define FCAPZ_{core_name}_VERSION_REG "
            f"{{`FCAPZ_VERSION_MAJOR, `FCAPZ_VERSION_MINOR, "
            f"`FCAPZ_{core_name}_CORE_ID}}"
        )
    lines += [
        "",
        "`endif  // FCAPZ_VERSION_VH",
        "",
    ]
    return "\n".join(lines)


def render_vhdl_package(major: int, minor: int, patch: int) -> str:
    """Build rtl/vhdl/pkg/fcapz_pkg.vhd from a parsed version."""
    lines: list[str] = [
        "-- SPDX-License-Identifier: Apache-2.0",
        "-- Copyright (c) 2026 Leonardo Capossio - bard0 design - <hello@bard0.com>",
        "--",
        "-- AUTO-GENERATED by tools/sync_version.py from the canonical VERSION file",
        "-- at the repo root.  DO NOT EDIT BY HAND -- bump VERSION and re-run",
        "--   python tools/sync_version.py",
        "-- CI runs the same script with --check and fails if this package drifts.",
        "",
        "library ieee;",
        "use ieee.std_logic_1164.all;",
        "",
        "package fcapz_pkg is",
        f"    constant FCAPZ_VERSION_MAJOR : std_logic_vector(7 downto 0) := x\"{major:02X}\";",
        f"    constant FCAPZ_VERSION_MINOR : std_logic_vector(7 downto 0) := x\"{minor:02X}\";",
        f"    constant FCAPZ_VERSION_PATCH : std_logic_vector(7 downto 0) := x\"{patch:02X}\";",
        "",
    ]
    for core_name, (ascii_id, description) in CORE_IDS.items():
        if len(ascii_id) != 2:
            raise ValueError(f"core_id {ascii_id!r} for {core_name} must be 2 ASCII chars")
        packed = (ord(ascii_id[0]) << 8) | ord(ascii_id[1])
        lines.append(
            f"    constant FCAPZ_{core_name}_CORE_ID : std_logic_vector(15 downto 0) := "
            f"x\"{packed:04X}\"; -- \"{ascii_id}\" - {description}"
        )
    lines.append("")
    for core_name in CORE_IDS:
        lines.append(
            f"    constant FCAPZ_{core_name}_VERSION_REG : std_logic_vector(31 downto 0) := "
            f"FCAPZ_VERSION_MAJOR & FCAPZ_VERSION_MINOR & FCAPZ_{core_name}_CORE_ID;"
        )
    lines += [
        "end package fcapz_pkg;",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Do not write; exit 1 if the generated header would differ "
             "from the on-disk file (used by CI to detect drift).",
    )
    args = parser.parse_args()

    if not VERSION_FILE.is_file():
        print(f"error: {VERSION_FILE} not found", file=sys.stderr)
        return 2

    raw = VERSION_FILE.read_text(encoding="utf-8")
    try:
        major, minor, patch = parse_version(raw)
    except ValueError as exc:
        print(f"error parsing VERSION: {exc}", file=sys.stderr)
        return 3

    version_str = f"{major}.{minor}.{patch}"
    generated = {
        HEADER_FILE: render_header(major, minor, patch, version_str),
        VHDL_PACKAGE_FILE: render_vhdl_package(major, minor, patch),
    }

    if args.check:
        drifted = []
        for path, content in generated.items():
            if not path.is_file():
                print(
                    f"error: {path} does not exist; "
                    "run `python tools/sync_version.py` to generate it.",
                    file=sys.stderr,
                )
                return 1
            if path.read_text(encoding="utf-8") != content:
                drifted.append(path)
        if drifted:
            paths = ", ".join(str(path.relative_to(ROOT)) for path in drifted)
            print(
                f"error: {paths} out of sync with VERSION ({version_str}). "
                "Run `python tools/sync_version.py` and commit the result.",
                file=sys.stderr,
            )
            return 1
        print(f"OK: HDL version constants are in sync with VERSION ({version_str})")
        return 0

    for path, content in generated.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path} ({version_str})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
